### ISSUE TITLE
Bot is bloat due to unnecessary dependencies

### ISSUE THREAD

**Issue by joaomagfreitas** [LuchoTurtle/banger-bot#11]
Escuse my dumby question, but do we need all these dependencies to run the bot? 😅

```
appdirs==1.4.4
APScheduler==3.6.3
beautifulsoup4==4.9.3
black==20.8b1
certifi==2020.11.8
cffi==1.14.4
chardet==3.0.4
click==7.1.2
cryptography==3.2.1
decorator==4.4.2
idna==2.10
linkpreview==0.1.11
mypy-extensions==0.4.3
pathspec==0.8.1
pycparser==2.20
python-decouple==3.3
python-telegram-bot==13.0
pytz==2020.4
regex==2020.11.13
requests==2.25.0
six==1.15.0
soupsieve==2.0.1
toml==0.10.2
tornado==6.1
typed-ast==1.4.1
typing-extensions==3.7.4.3
tzlocal==2.1
urllib3==1.26.2
```

It seems pip is installing dependencies to run a webserver (`tornado`), but we are not depending on it (although that python-telegram-bot depends on it). We should only rely on really needed dependencies, dev dependencies that facilitate our workflow and the telegram api wrapper itself(`python-telegram-bot`).

**Comment by LuchoTurtle** [comment]
This is normal behaviour, as found [here](https://stackoverflow.com/questions/59959344/how-can-i-optimize-my-requirements-txt-to-include-only-the-packages-my-applicati), for example. @RicardoSilveira23 can get into detail but since he installed on an empty venv, the dependencies should be fine :)

**Comment by joaomagfreitas** [comment]
> This is normal behaviour, as found [here](https://stackoverflow.com/questions/59959344/how-can-i-optimize-my-requirements-txt-to-include-only-the-packages-my-applicati), for example. @RicardoSilveira23 can get into detail but since he installed on an empty venv, the dependencies should be fine :)

Oh okay, didn't know about that! My bloat trigger is now off :)
