### ISSUE TITLE
Shazam-like song name detection

### ISSUE THREAD

**Issue by LuchoTurtle** [LuchoTurtle/banger-bot#8]
This is an idea and not part of the MVP.

...but it would be SUUUUUPER neat if we had this on! Imagine if a user records a song (sends a voice message) to the group chat and asks the bot to analyze it so they know which song it is. That would be dope!

Does Shazam have an API or something of the sort we could use? 🤔

**Comment by dotX12** [comment]
Hi, @LuchoTurtle it's possible!
https://github.com/dotX12/ShazamIO
Is a FREE asynchronous framework from reverse engineered Shazam API written in Python 3.7 with asyncio and aiohttp.
